version: '2'
services:
  db:
    container_name: md-db
    image: redis:3.2.1-alpine
    volumes:
      - /data/md-db:/data
    ports:
      - 6379:6379
    environment:
      USER: user
      PASSWORD: password
    command: redis-server --appendonly yes
